"""Hermes-Lite: Lightweight tool-execution framework for LLM agents."""

from hermes_lite.registry import PluginRegistry, ToolDefinition, ToolError, ToolNotFoundError, ToolValidationError
from hermes_lite.memory import (
    AsyncSQLitePool,
    ensure_schema,
    create_session,
    get_session,
    update_session,
    delete_session,
    list_sessions,
    insert_message,
    get_messages,
    get_message_count,
    delete_messages,
    set_metadata,
    get_metadata,
    list_metadata,
    delete_metadata,
    session_context,
)
from hermes_lite.router import LiteRouter, RoutingDecision, parse_fallback_chain
from hermes_lite.orchestrator import HermesOrchestrator
from hermes_lite.cli import run_cli, PromptHandler
from hermes_lite.tools_builtins import (
    register_builtins,
    ESSENTIAL_TOOL_NAMES,
    ToolResult,
    ReadFileArgs,
    SearchFilesArgs,
    TerminalArgs,
    MemoryArgs,
    WebSearchArgs,
    WebFetchArgs,
)
from hermes_lite.observability import (
    log_turn,
    read_turns,
    compute_stats,
    print_stats,
    DEFAULT_LOG_DIR,
    DEFAULT_LOG_FILE,
    MAX_LOG_BYTES,
)
from hermes_lite.subagent import (
    SubagentArgs,
    SubagentRunner,
    register_subagent_tool,
    SUBAGENT_TOOL_NAME,
    SUBAGENT_MAX_TOOL_CALLS,
    SUBAGENT_MAX_ITERATIONS,
    SUBAGENT_WALL_TIMEOUT_S,
    SUBAGENT_SYSTEM_PROMPT,
)
from hermes_lite.llm import (
    ChatRequest,
    ChatResponse,
    Tier,
    chat,
    tool_def,
    parse_tool_calls_from_text,
    RateLimiter,
    APIKeyRotator,
    AllKeysExhausted,
    get_rate_limiter,
    get_key_rotator,
    DEFAULT_RPM,
    DEFAULT_MAX_RETRIES,
)
from hermes_lite.moa import (
    MoAEngine,
    MoAPreset,
    MoAModelConfig,
    MoAResult,
    BUILTIN_PRESETS,
    get_preset,
    list_presets as list_moa_presets,
    format_preset_info,
    format_moa_result,
)

__all__ = [
    "PluginRegistry",
    "ToolDefinition",
    "ToolError",
    "ToolNotFoundError",
    "ToolValidationError",
    "AsyncSQLitePool",
    "ensure_schema",
    "create_session",
    "get_session",
    "update_session",
    "delete_session",
    "list_sessions",
    "insert_message",
    "get_messages",
    "get_message_count",
    "delete_messages",
    "set_metadata",
    "get_metadata",
    "list_metadata",
    "delete_metadata",
    "session_context",
    "LiteRouter",
    "RoutingDecision",
    "parse_fallback_chain",
    "HermesOrchestrator",
    "run_cli",
    "PromptHandler",
    # LLM layer
    "ChatRequest",
    "ChatResponse",
    "Tier",
    "chat",
    "tool_def",
    "parse_tool_calls_from_text",
    "RateLimiter",
    "APIKeyRotator",
    "AllKeysExhausted",
    "get_rate_limiter",
    "get_key_rotator",
    "DEFAULT_RPM",
    "DEFAULT_MAX_RETRIES",
    # 6 essentials
    "register_builtins",
    "ESSENTIAL_TOOL_NAMES",
    "ToolResult",
    "ReadFileArgs",
    "SearchFilesArgs",
    "TerminalArgs",
    "MemoryArgs",
    "WebSearchArgs",
    "WebFetchArgs",
    # Observability (T12)
    "log_turn",
    "read_turns",
    "compute_stats",
    "print_stats",
    "DEFAULT_LOG_DIR",
    "DEFAULT_LOG_FILE",
    "MAX_LOG_BYTES",
    # Subagent (T8)
    "SubagentArgs",
    "SubagentRunner",
    "register_subagent_tool",
    "SUBAGENT_TOOL_NAME",
    "SUBAGENT_MAX_TOOL_CALLS",
    "SUBAGENT_MAX_ITERATIONS",
    "SUBAGENT_WALL_TIMEOUT_S",
    "SUBAGENT_SYSTEM_PROMPT",
    # MoA
    "MoAEngine",
    "MoAPreset",
    "MoAModelConfig",
    "MoAResult",
    "BUILTIN_PRESETS",
    "get_preset",
    "list_moa_presets",
    "format_preset_info",
    "format_moa_result",
]